version: 2.0
jobs:
  test1:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test2:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World 2!'
            echo 'This is the delivery pipeline 2'
workflows:
  version: 2
  test1_test2:
    jobs:
      - test1
      - test2